apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "debug"
  MESSAGE: "Hello, world from ConfigMap!"
  app-settings.json: |
    {
      "featureFlags":
      {
        "betaMode": true,
        "metricsEnabled": true
      }
    }
