apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  restartPolicy: Never
  containers:
  - image: snowflake-nextid:1.0
    name: app
    env: # Параметры из ConfigMap подключаются как переменные окружения
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: LOG_LEVEL
      - name: MESSAGE
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: MESSAGE
    volumeMounts: # Параметры из ConfigMap подключаются как файл из хранилища
      - name: app-config-volume
        mountPath: /config
        readOnly: true
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
  volumes: # Подключение ConfigMap к объекту Pod
    - name: app-config-volume
      configMap:
        name: app-config
