apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  LOG_LEVEL: "debug"
  MESSAGE: "Hello from ConfigMap"
  spring.application.name: "snowflake-id-generator"
  snowflake-settings.starting-epoch: "1577836800000"
  snowflake-settings.datacenter-id: "1"
  app-settings.json: |
    {
      "featureFlags":
      {
        "betaMode": true,
        "metricsEnabled": true
      }
    }
