apiVersion: v1
kind: Secret
metadata:
  name: kuard-tls
type: kubernetes.io/tls
stringData:
  tls.crt:
    -----BEGIN CERTIFICATE-----
    MIIF0zCCA7ugAwIBAgIUXVzbyFjDJFein/Yw4KT4I95jFB8wDQYJKoZIhvcNAQEL
    BQAweTELMAkGA1UEBhMCUlUxDDAKBgNVBAgMA3NwYjEMMAoGA1UEBwwDc3BiMQ0w
    CwYDVQQKDARob21lMQ0wCwYDVQQLDARob21lMQ4wDAYDVQQDDAVhbGV4azEgMB4G
    CSqGSIb3DQEJARYRdGVzdDEyM0BnbWFpbC5jb20wHhcNMjYwMzEyMTk1MjMyWhcN
    MjcwMzEyMTk1MjMyWjB5MQswCQYDVQQGEwJSVTEMMAoGA1UECAwDc3BiMQwwCgYD
    VQQHDANzcGIxDTALBgNVBAoMBGhvbWUxDTALBgNVBAsMBGhvbWUxDjAMBgNVBAMM
    BWFsZXhrMSAwHgYJKoZIhvcNAQkBFhF0ZXN0MTIzQGdtYWlsLmNvbTCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBALoOCrc4cXvfisYYyRY6xzuRgvOr7WI7
    PpeL7A7awcEeaRErwDHj9Xqgc1V2bWxZVTD5QBcCictsaAyJOI9AyPCBqz+XTSbU
    TlgXTGuXR61W45RCirPsF3Lqcb/GK7aTM44XiI5QPLWkqVwekMJeWkV+sewVsigD
    vrmhvR/I+J2fO6s9NYB6LX2Du1IVqln5MKZU8Ux+WP5T+gv+7b8rDI1p2BwCSXeV
    S3TYawtyhnJeVOQLjOp9398xPOUqaRakFHJscUqqFSls9PJPEbd47lLWXWEKd3cA
    AkXJF2kyD+kgvd0YpaRxFLnU+qHHNMwMK/5u5NZeTd9reFtSYO3QKZnMLF6qtVWt
    EMl9ZxNyKiFPHvP8Ahn8eKqk2JJyyvzNo/Ti7bStFpBfI+PSRKojxLykK9JBrS6P
    w3RSr6zUPPeQw65CH038uhvUAmzll60oIpiZjlulk3uiBuF6ef0HOB7Othwo/4el
    nPP6e8EBm5e8EoTTDk+nMPlYFfu7dnE06f98jD9hmiCEQ5eLQ7uJCR2jXXjY78LR
    rGtxCSN2N1Dv0XiD/BB4m/13UuxjKP1/m1R9h8rR6CxHItjDQHqY2vRy26BBEgWD
    OyQyIQeWRPK097Hktnq0yZHNrLbl6KIrqadUoTH+eQ7bc5CCkpYwCzTt5gbEhMl9
    8GarGljZUuDvAgMBAAGjUzBRMB0GA1UdDgQWBBRLXkVp9Hdmsr/4waT9Fhb2sh0x
    UTAfBgNVHSMEGDAWgBRLXkVp9Hdmsr/4waT9Fhb2sh0xUTAPBgNVHRMBAf8EBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4ICAQChTxD7hxyTVonLGjyW2CfWfFpQdJwaMsg8
    sNk7BHcfVHK9et7hToW9IOAm5eBwirDKZM2lhrVf45cy8wJ44TgPFl/bkl9qTAf5
    7JxnPUHAS0OiVmXO8RY1WrR6Cdp5ktr6IwsFLoAhwRJ8iX6n79fyjHtzJZoFbR58
    bkfMUb6k95lNt+VnJf5ye02Ly9ro3BmZLuFGRfIpyy1mP2qtdU3RewioIRcHJ3Rw
    0e0K6iWVyvGe2UjQ1TCNVi0epK7elxygajcvbcjApU0PY7XKqYjscsvDZpPc20q6
    ypiZg73oIGTKol+yAYLFiCCYB80gLyYJZtVjJTDdgASX6lTzGv8olp95z8R8Ky2S
    TWsTA9AetqaifCxV9wb6iqOYvkSXxvAW/SQdIBZV49ZwclUfTAXdRHJ7kUKbpv6F
    H/LoTmZ8dVkeQaDLUCK93xK5sZXEOZtO3wAReJWObCFa3MbpUi/5ifd5tny2vqBk
    N5AQBplI3YXDIfmeG4360DLl9tDOOTI7VkhSY7MsZBQfS5a/FBYu5ksHvgia9A8S
    X2hxGNXxs9ec+fG6SXs7W9Nvb9xzqh/3A9/S3hiWWFoQnUlzqNv+XeTBEnORfKwx
    g1vEgR+zPdNRqd5B/DikwcMb88I89tCYDALFJwtsdpbt1+o6bPAb+d5ZZOab8/+D
    y0alBbLYWg==
    -----END CERTIFICATE-----
  tls.key:
    -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIIJtTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQKSVo9bOrlr0zMgFr
    ytzfegICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEFIO4SeapXPMlUtV
    La5RhZ4EgglQXMg3DL4YbPJDMtxhF+uEQneYC1oRV1BPxSMq5mlq4KCaYUI2RL1w
    u4N5eK/tjw1y2ejtf4BuI3X+li1HJqDDo1Nf95WU8kHtNdedjqcNs//P9qRqqM1y
    wuXXhq9yLAJzQNG4RF87tOuDJBfQTxVPvlDSNAkRCWueS/PvE0v45VPLnA/4A4lt
    6UGHhEtcs78/njV3xCc7U+Q1VEQd2qCDAuAjeM/2MSbEWQbFIVMPwnexSMQGH0y2
    Y9RPcFpd0Qr7iJYlCq+WA6+Jthz7jcyNB09XnK4YyIMSikS9/KIDERT5T2FYSc+E
    GMV1QUTu3jFLhh0MLk+uYh0i5U4t/E2Fe2YBo+8f93kr+HlSSedbORhN4ChdYc3g
    X82BeoWe+eRZDwaKUMmx2YBZE6yvrMz8xJgi9m+8j244VCQKaeNRKDdkeaD+z9NV
    5UL63uffW7+rshvf+ujdy8wOO/2sFpM4YodcLGWxgy15XvElb+NyRjZhSDD9zH/l
    bqnSK50+LpKlKlHLyGgbwnWIdpyCmGM4T1pPePxO7wFRxXsXMPJZ848iq6i2h0b3
    iXZ627ow1wK/ORFvp4maSYbI+ncQSk5LAWFAvuHlYP5RaRzuqoDmmtyly/qKAYyn
    4dwPJ/DRnTDNcjI4+r5qTLMt4vVBqPNbdMUjQZLeZyUTn8JkFprkLs2nsoKIHTp/
    Lwohwf0z0btIL7PYprf3M0Nt9K225X0ob/a5CUI1eO117x5241XouphBSA7UA57M
    w+1WYxzE/g0F8KtSLteLllquq+2N/mF9kNTOrIFABDIwh582DElc5sWMBSHL8k5q
    QT/fAhI0Te98FH0nMgA7ACC4vlSPaCB4FJhLU/MXYEyd5iJo5qOcpy47ErluOyAZ
    /0sE/2qWgDnfbzf4MFTpatbFOlvZIKd8XPooWonuGlT2IapEQhnYDITiXeUguv3b
    w6ewrSCtwvPa/8lIK5zPB9GBNJLzWqM023NE/pdIuvQ0yPjwiE5pU0wU82uxD/g2
    qWfTBoAstprPcPZuyKlcLkP2adhOc8FMV6q2R6bYIWtKmQ1sHXYwbf6sL7/nJEv5
    W1oWSeMx2BJ0UqNSxObullfQlVx2Mn1GQQ0L2T5ffZ/3ibShm/1M2Mg8sKS/dkj2
    6j+lNoLbHeP4tNZoPy2VEfHSjLEovpzJco8OBry0UCd6nU0xpFoUaclkJy5oMTGg
    bE/YiTtbvOGbwq09/aD8HR1aVoXJ3PKBIcuFJ76AcqkPxqk4rXb8VMc6OngzOUaX
    DHmIa3wnnrhJGQe18d1GvdixdDmEi2He/vOcKHaYnB+HyVaVvAdBCGDB71tRF8bO
    uNaDOAVVMD8NmZ5RvDJkhkeX9l4VNmoNrnhcRWFHkx4ulqKX7jb/BiiegtDxpBvq
    H0Djq3i/7W2CKmvrJCWgyFSQOwLCg1MxSvpbmbhqA/QwzTcqIlsmtc3nTanNiYrN
    iW/fA06z7yKDHH6GgqGwXWJXKxeuqprej+wrHsXXozoHAQKv1RulFS21q9XVRkq8
    vmWi/spBUroeTuknmyaDN1QGjeeOb29GHiksj5XNeGR0lmsXkcki1U3GJ0P8/3CS
    f+qwYZ9S0mGBUQcYi5zci9alqgSuzZUBeepuOQ6oDUG3TeDdDzXMdcgtdnVelQDZ
    cVs2qeRMWHZhyEToDc1I0rKsMN7NN+C1Ms4gE54640pLtPrd1BaZ6Xs5zX78TORS
    JwXHObCFlJkwmoinEgnTOs7IYoRkS5JhoPPFKJI50yOzN5mV0D+XvQIPS2D2BFEh
    AfzaNZjmlyuh7LpjHWFwTy0pDvUIqxwJ8i73LuINaMFsxKjtkln758ezHD0yQPUT
    suXrhfPzPm+eev5ros49b0/isNTMgzX8Vyk7sIUFf8tG7xdBkLj0jxL/p5bVibTX
    QjgtDubsr+UslB82Mu1SlWgTNq3F1dl0xHZhS7Fu544+Rsfdm44cH7VV9z/U9Tf/
    IkejQHPD2tqNDxOEcHFwoIKO4edo9e9mI6vGxPM+/kAw1D5OgHVV0a1dcxEo9FF9
    YL7b5OKKnW69JQFh/WKk2hHT9NveGiAENYl993ItK/l4EIdsbclgwS40buBbJOkp
    fefddPdWIza+Wy4bZsU38/BRv5n8MceWEP0lTxhUk1RsaW82PV4GatgbXa77kti6
    73nkFgh4btaoIn6GeeVoTfqWpAjyk4Rmo6uza1r169mEFSA+kvhrIQrWh9hw6AD2
    isOL/QcpSQ7/INviyax6RHARIa4FuCAaD8wAoBEK9n4MxP3t9Om9j3eLjkAa26Co
    CYavoNk1OsHusiRqMtIwdmTFKkCkoIRr5cJF48g1QrTrV26X6xJUhoySoQsQDj5b
    xmWe9iwsAU1QCVqm1PrP18vhZ4diH5ugI7IqBPhOXpA5rXR9jW1vMYqD9h7E9Ahs
    X05DByg//6VFFCqsk8nxgH1bqTA6J7mD5GvydeNbBXkXA6iMf5zMrIu2EA9Uqo0f
    dthrLgMle1/3v9gSLfsQG8yoNLO3IW+ycrREIkmyXqJ6DB3W59C0MxdpexIPlZlE
    RwnY5E8vwWD4KOyLyvyd4dWo4cTglWGCULTREAwEXkc8vMItjnOCFKTShPFp1rIx
    iSB4iq1eNOjALDlis5FKYKBOOKoVhi7UjMlnRYUyIJTDNWGTBwVKpdnpFxBfY0tD
    I7INVL9wlOhFPg8kMtqDM+2Hq8sBVY81FyUX55dKM9ifQ6bOeH2bN2K4dQU/Mfmw
    vmWgaPZzw18k7WxunBMqFbhFc79VVry8z6m0YSetnTEoww0cdmExGrkHE3lFQ2bC
    geaRmT/jmWUC1dYdWkzZfFoqSCVtzDBdCqE4OcIAwaSR5uhut8ZnKSNIefrSjJRQ
    zDK4yGOqQICBlqQ1Cpvgsph9fIwg7wziFtpYsnGjI4osrTAaaRH82q1LO1NIWf2h
    cz6V93VddFe7LDICHcUhg+qnLHrnqyVp/GOXq08YwUVy9uZ3IS6UOD76P9rRImZB
    mm1jqQQoWrXTfJwgVDHMqKEqh0uw0LTItNhcIdn62C/++KhBF3qijWZF225DJUNw
    EEP6yPO5B1wPu9YpiyXtqhU4LmNp3Mhqe60jj+0X887+N5ENOPGcLzTsx0oByQ5o
    5TW4II6Ib6mtzULbwA/hnbjHiIEBGmfIwsRimAqdPk0Rwta1guxQFLI=
    -----END ENCRYPTED PRIVATE KEY-----
